"use strict";
// Lightweight update network compatibility layer: prefer fresh GitHub raw bytes, use jsDelivr only as fallback.
const https=require("https");
const {EventEmitter}=require("events");
const originalGet=https.get.bind(https);
function bufferedGet(url,headers,done){return originalGet(url,{headers:{"User-Agent":"A-Temir-Stroy-Report","Cache-Control":"no-cache","Pragma":"no-cache",...(headers||{})}},res=>{if(res.statusCode!==200){res.resume();done(new Error("HTTP "+res.statusCode));return}const chunks=[];res.on("data",c=>chunks.push(c));res.on("end",()=>done(null,Buffer.concat(chunks)))}).on("error",done)}
function fakeResponse(data,cb,type){const r=new EventEmitter();r.statusCode=200;r.headers={"content-length":String(data.length),"content-type":type||"application/octet-stream"};r.resume=()=>{};cb(r);process.nextTick(()=>{r.emit("data",data);r.emit("end")})}
function getWithFallback(primary,fallback,headers,cb,transform){return bufferedGet(primary,headers,(e,d)=>{if(!e){const o=transform?transform(d):d;fakeResponse(o,cb,transform?"application/json":"application/octet-stream");return}bufferedGet(fallback,headers,(e2,d2)=>{if(e2){const r=new EventEmitter();r.statusCode=503;r.headers={};r.resume=()=>{};cb(r);process.nextTick(()=>r.emit("end"));return}const o=transform?transform(d2):d2;fakeResponse(o,cb,transform?"application/json":"application/octet-stream")})})}
https.get=function patchedGet(input,options,callback){let cb=callback,opts=options;if(typeof options==="function"){cb=options;opts=undefined}let url;try{url=input instanceof URL?input:new URL(String(input))}catch{return originalGet(input,options,callback)}
if(url.hostname==="raw.githubusercontent.com"){const p=url.pathname.split("/").filter(Boolean);if(p.length>=4){const owner=p.shift(),repo=p.shift(),ref=p.shift(),parts=p.slice();const raw=`https://raw.githubusercontent.com/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/${encodeURIComponent(ref)}/${parts.map(encodeURIComponent).join("/")}?t=${Date.now()}`;const cdn=`https://cdn.jsdelivr.net/gh/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}@${encodeURIComponent(ref)}/${parts.map(encodeURIComponent).join("/")}?v=${Date.now()}`;return getWithFallback(raw,cdn,opts?.headers||{},cb)}}
if(url.hostname==="api.github.com"){const m=url.pathname.match(/^\/repos\/([^/]+)\/([^/]+)\/contents\/(.+)$/);if(m){const owner=decodeURIComponent(m[1]),repo=decodeURIComponent(m[2]),parts=m[3].split("/").map(decodeURIComponent),ref=url.searchParams.get("ref")||"main";const raw=`https://raw.githubusercontent.com/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/${encodeURIComponent(ref)}/${parts.map(encodeURIComponent).join("/")}?t=${Date.now()}`;const cdn=`https://cdn.jsdelivr.net/gh/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}@${encodeURIComponent(ref)}/${parts.map(encodeURIComponent).join("/")}?v=${Date.now()}`;return getWithFallback(raw,cdn,opts?.headers||{},cb,d=>Buffer.from(JSON.stringify({type:"file",encoding:"base64",content:d.toString("base64"),size:d.length})))}}
return originalGet(input,options,callback)};
require("./main.js");
