const {app,BrowserWindow,ipcMain,dialog}=require("electron");
const path=require("path"),fs=require("fs"),Database=require("better-sqlite3"),XLSX=require("xlsx");
let win,db;
function initDb(){const dir=app.getPath("userData");fs.mkdirSync(dir,{recursive:true});const dbPath=path.join(dir,"smetriqo.sqlite"),legacyDbPath=path.join(dir,["a","temir"].join("")+".sqlite");if(!fs.existsSync(dbPath)&&fs.existsSync(legacyDbPath)){fs.copyFileSync(legacyDbPath,dbPath);for(const ext of ["-wal","-shm"]){const src=legacyDbPath+ext,dst=dbPath+ext;if(fs.existsSync(src))fs.copyFileSync(src,dst)}}db=new Database(dbPath);db.pragma("journal_mode=WAL");db.exec("CREATE TABLE IF NOT EXISTS state(id INTEGER PRIMARY KEY,json TEXT NOT NULL,updated TEXT NOT NULL);CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,json TEXT NOT NULL,updated TEXT NOT NULL);CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS objects(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,json TEXT NOT NULL,updated TEXT NOT NULL);CREATE TABLE IF NOT EXISTS daily_reports(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,report_date TEXT NOT NULL,json TEXT NOT NULL,updated TEXT NOT NULL,UNIQUE(object_id,report_date),FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE)");db.pragma("foreign_keys=ON");
 db.exec("CREATE TABLE IF NOT EXISTS companies(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,json TEXT NOT NULL,updated TEXT NOT NULL)");
 const companyCols=db.prepare("PRAGMA table_info(objects)").all();if(!companyCols.some(x=>x.name==="company_id"))db.exec("ALTER TABLE objects ADD COLUMN company_id INTEGER");
 let defaultCompany=db.prepare("SELECT id FROM companies ORDER BY id LIMIT 1").get();if(!defaultCompany){let profile={name:"Моя компания",bin:"",director:"",phone:"",email:"",address:"",iban:"",bic:"",kbe:"",bankName:"",bank:"",logo:""};const old=db.prepare("SELECT json FROM objects ORDER BY id LIMIT 1").get();if(old){try{const d=JSON.parse(old.json);profile.name=d.companyName||profile.name;profile.logo=d.companyLogo||""}catch(e){}}const q=db.prepare("INSERT INTO companies(name,json,updated) VALUES(?,?,datetime('now'))").run(profile.name,JSON.stringify(profile));defaultCompany={id:Number(q.lastInsertRowid)}}db.prepare("UPDATE objects SET company_id=? WHERE company_id IS NULL").run(defaultCompany.id);
 const migrated=db.prepare("SELECT value FROM meta WHERE key='legacy_state_migrated'").get();
 if(!migrated){const count=db.prepare("SELECT COUNT(*) n FROM reports").get().n;if(!count){const old=db.prepare("SELECT json FROM state WHERE id=1").get();if(old){try{const d=JSON.parse(old.json),name=d.object||d.objectName||"Первый отчёт";db.prepare("INSERT INTO reports(name,json,updated) VALUES(?,?,datetime('now'))").run(name,JSON.stringify(d))}catch(e){}}}db.prepare("INSERT OR REPLACE INTO meta(key,value) VALUES('legacy_state_migrated','1')").run()}}

function migrateObjects(){const done=db.prepare("SELECT value FROM meta WHERE key='objects_v1_migrated'").get();if(done)return;const defaultCompany=db.prepare("SELECT id FROM companies ORDER BY id LIMIT 1").get();const rows=db.prepare("SELECT id,name,json,updated FROM reports ORDER BY id").all(),insObj=db.prepare("INSERT INTO objects(name,json,updated) VALUES(?,?,?)"),insDay=db.prepare("INSERT OR IGNORE INTO daily_reports(object_id,report_date,json,updated) VALUES(?,?,?,?)");for(const r of rows){try{const d=JSON.parse(r.json),date=d.reportDate||new Date().toISOString().slice(0,10),project={companyName:d.companyName||'',object:d.object||d.objectName||r.name,address:d.address||'',client:d.client||d.customer||'',companyLogo:d.companyLogo||'',workTypes:d.workTypes||[],tasks:d.tasks||[],deadlines:d.deadlines||[],financeContracts:d.financeContracts||[],financeActs:d.financeActs||[],financePasswordHash:d.financePasswordHash||'',participants:d.participants||[]},daily={reportDate:date,weather:d.weather||{},workDays:d.workDays||[],invoices:d.invoices||[],workers:d.workers||[],responsibles:d.responsibles||[],equipment:d.equipment||[],actedDays:d.actedDays||[],penalties:d.penalties||[],reportPhotos:d.reportPhotos||[],reportSections:d.reportSections||{}};const o=insObj.run(project.object||r.name,JSON.stringify(project),r.updated||new Date().toISOString());if(defaultCompany)db.prepare("UPDATE objects SET company_id=? WHERE id=?").run(defaultCompany.id,Number(o.lastInsertRowid));insDay.run(Number(o.lastInsertRowid),date,JSON.stringify(daily),r.updated||new Date().toISOString())}catch(e){}}db.prepare("INSERT OR REPLACE INTO meta(key,value) VALUES('objects_v1_migrated','1')").run()}
function create(){win=new BrowserWindow({width:1500,height:930,minWidth:1000,minHeight:650,autoHideMenuBar:true,backgroundColor:"#eef3f7",webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,"src","index.html"));}
app.whenReady().then(()=>{initDb();migrateObjects();const firstCompany=db.prepare("SELECT id FROM companies ORDER BY id LIMIT 1").get();if(firstCompany)db.prepare("UPDATE objects SET company_id=? WHERE company_id IS NULL").run(firstCompany.id);create()});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});
ipcMain.handle("db:reports",()=>db.prepare("SELECT id,name,updated FROM reports ORDER BY datetime(updated) DESC,id DESC").all());
ipcMain.handle("db:reportAnalytics",()=>db.prepare("SELECT id,name,updated,json FROM reports ORDER BY datetime(updated) DESC,id DESC").all().map(r=>{try{return{id:r.id,name:r.name,updated:r.updated,data:JSON.parse(r.json)}}catch(e){return{id:r.id,name:r.name,updated:r.updated,data:null}}}));
ipcMain.handle("db:createReport",(_,name)=>{const d={object:name||"Новый отчёт"};const r=db.prepare("INSERT INTO reports(name,json,updated) VALUES(?,?,datetime('now'))").run(name||"Новый отчёт",JSON.stringify(d));return Number(r.lastInsertRowid)});
ipcMain.handle("db:duplicateReport",(_,id)=>{const r=db.prepare("SELECT name,json FROM reports WHERE id=?").get(id);if(!r)return null;let d;try{d=JSON.parse(r.json)}catch(e){return null}const name=(r.name||"Отчёт")+" — копия";d.object=name;const q=db.prepare("INSERT INTO reports(name,json,updated) VALUES(?,?,datetime('now'))").run(name,JSON.stringify(d));return Number(q.lastInsertRowid)});
ipcMain.handle("db:deleteReport",(_,id)=>{db.prepare("DELETE FROM reports WHERE id=?").run(id);return true});
ipcMain.handle("db:load",(_,id)=>{const r=id?db.prepare("SELECT json FROM reports WHERE id=?").get(id):db.prepare("SELECT json FROM reports ORDER BY datetime(updated) DESC,id DESC LIMIT 1").get();if(!r)return null;try{return JSON.parse(r.json)}catch(e){return null}});
ipcMain.handle("db:save",(_,id,d)=>{if(!id)return false;const name=d.object||d.objectName||"Без названия";db.prepare("UPDATE reports SET name=?,json=?,updated=datetime('now') WHERE id=?").run(name,JSON.stringify(d),id);return true});
ipcMain.handle("file:import",async()=>{const r=await dialog.showOpenDialog(win,{properties:["openFile"],filters:[{name:"SaveFiles",extensions:["json"]}]});return r.canceled?null:JSON.parse(fs.readFileSync(r.filePaths[0],"utf8"))});
ipcMain.handle("file:backup",async(_,d)=>{const r=await dialog.showSaveDialog(win,{defaultPath:"Smetriqo_резервная-копия.json",filters:[{name:"JSON",extensions:["json"]}]});if(r.canceled)return false;fs.writeFileSync(r.filePath,JSON.stringify(d,null,2));return true});
ipcMain.handle("file:html",async(_,h)=>{const r=await dialog.showSaveDialog(win,{defaultPath:"Smetriqo.html",filters:[{name:"HTML",extensions:["html"]}]});if(r.canceled)return false;fs.writeFileSync(r.filePath,h);return true});
ipcMain.handle("file:pdf",async(_,html)=>{const r=await dialog.showSaveDialog(win,{defaultPath:"Smetriqo.pdf",filters:[{name:"PDF",extensions:["pdf"]}]});if(r.canceled)return false;const pw=new BrowserWindow({show:false,webPreferences:{contextIsolation:true,nodeIntegration:false}}),tmp=path.join(app.getPath("temp"),"smetriqo-"+Date.now()+".html");try{fs.writeFileSync(tmp,html,"utf8");await pw.loadFile(tmp);const b=await pw.webContents.printToPDF({printBackground:true,pageSize:"A4",preferCSSPageSize:true,margins:{top:0.35,bottom:0.35,left:0.35,right:0.35}});fs.writeFileSync(r.filePath,b);return true}finally{pw.destroy();try{fs.unlinkSync(tmp)}catch(e){}}});
ipcMain.handle("file:logo",async()=>{
 const r=await dialog.showOpenDialog(win,{properties:["openFile"],filters:[{name:"Images",extensions:["png","jpg","jpeg","webp"]}]});
 if(r.canceled)return null;
 const p=r.filePaths[0], ext=path.extname(p).toLowerCase().replace(".","")||"png";
 const mime=ext==="jpg"||ext==="jpeg"?"image/jpeg":ext==="webp"?"image/webp":"image/png";
 return "data:"+mime+";base64,"+fs.readFileSync(p).toString("base64");
});

ipcMain.handle("file:photos",async()=>{
 const r=await dialog.showOpenDialog(win,{properties:["openFile","multiSelections"],filters:[{name:"Images",extensions:["png","jpg","jpeg","webp"]}]});
 if(r.canceled)return [];
 return r.filePaths.slice(0,12).map(p=>{const ext=path.extname(p).toLowerCase();const mime=ext===".png"?"image/png":ext===".webp"?"image/webp":"image/jpeg";return "data:"+mime+";base64,"+fs.readFileSync(p).toString("base64")});
});

ipcMain.handle("file:bom",async()=>{
 const r=await dialog.showOpenDialog(win,{properties:["openFile"],filters:[{name:"Excel",extensions:["xlsx","xls","xlsm"]}]});
 if(r.canceled)return null;
 const wb=XLSX.readFile(r.filePaths[0],{cellDates:false});
 let chosen=wb.SheetNames[0],raw=[];
 for(const sn of wb.SheetNames){const rr=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:""});const ok=rr.some(row=>row.some(v=>/марка/i.test(String(v)))&&row.some(v=>/колич|кол-во/i.test(String(v))));if(ok){chosen=sn;raw=rr;break}}
 if(!raw.length)raw=XLSX.utils.sheet_to_json(wb.Sheets[chosen],{header:1,defval:""});
 const clean=s=>String(s??"").trim().toLowerCase().replace(/ё/g,"е");
 let hi=raw.findIndex(row=>row.some(v=>/марка/.test(clean(v)))&&row.some(v=>/наимен/.test(clean(v))));
 if(hi<0)hi=0;
 const head=raw[hi].map(clean);
 const col=(tests)=>head.findIndex(h=>tests.some(t=>t.test(h)));
 const mi=col([/^марка/,/позици/]), ni=col([/наимен/]), qi=col([/колич/,/^кол-во/]), wi=col([/вес.*1/,/масса.*1/,/вес.*ед/]), ti=col([/общ.*вес/,/итого.*вес/,/общ.*мас/]);
 if(mi<0||qi<0)throw new Error("Не найдены обязательные колонки «Марка» и «Количество».");
 const num=v=>{const n=Number(String(v??"").replace(/\s/g,"").replace(",","."));return Number.isFinite(n)?n:0};
 const rows=raw.slice(hi+1).map(r=>({mark:String(r[mi]??"").trim(),name:ni>=0?String(r[ni]??"").trim():"",qty:num(r[qi]),weight1:wi>=0?num(r[wi]):0,totalWeight:ti>=0?num(r[ti]):0})).filter(x=>x.mark&&x.qty>0);
 if(!rows.length)throw new Error("Ведомость распознана, но строки с марками и количеством не найдены.");
 return {sheet:chosen,rows,file:path.basename(r.filePaths[0])};
});

ipcMain.handle("db:companies",()=>db.prepare("SELECT id,name,updated,json FROM companies ORDER BY name,id").all().map(r=>{let data={};try{data=JSON.parse(r.json)}catch(e){}return{id:r.id,name:r.name,updated:r.updated,data}}));
ipcMain.handle("db:createCompany",(_,name)=>{const n=String(name||"Новая компания").trim()||"Новая компания",d={name:n,bin:"",director:"",phone:"",email:"",address:"",iban:"",bic:"",kbe:"",bankName:"",bank:"",logo:""};const r=db.prepare("INSERT INTO companies(name,json,updated) VALUES(?,?,datetime('now'))").run(n,JSON.stringify(d));return Number(r.lastInsertRowid)});
ipcMain.handle("db:saveCompany",(_,id,d)=>{if(!id)return false;const name=String(d.name||"Без названия").trim()||"Без названия";db.prepare("UPDATE companies SET name=?,json=?,updated=datetime('now') WHERE id=?").run(name,JSON.stringify(d),id);return true});
ipcMain.handle("db:deleteCompany",(_,id)=>{const count=db.prepare("SELECT COUNT(*) n FROM companies").get().n;if(count<=1)throw new Error("Нельзя удалить единственную компанию.");const used=db.prepare("SELECT COUNT(*) n FROM objects WHERE company_id=?").get(id).n;if(used)throw new Error("Сначала удалите или перенесите объекты этой компании.");db.prepare("DELETE FROM companies WHERE id=?").run(id);return true});
ipcMain.handle("db:objects",(_,companyId)=>db.prepare("SELECT o.id,o.name,o.updated,COUNT(d.id) reportCount,MAX(d.report_date) lastReportDate FROM objects o LEFT JOIN daily_reports d ON d.object_id=o.id WHERE o.company_id=? GROUP BY o.id ORDER BY datetime(o.updated) DESC,o.id DESC").all(companyId));
ipcMain.handle("db:createObject",(_,name,companyId)=>{const n=String(name||'Новый объект').trim()||'Новый объект',d={object:n,participants:[]};const r=db.prepare("INSERT INTO objects(name,json,updated,company_id) VALUES(?,?,datetime('now'),?)").run(n,JSON.stringify(d),companyId);return Number(r.lastInsertRowid)});
ipcMain.handle("db:loadObject",(_,id)=>{const r=db.prepare('SELECT json FROM objects WHERE id=?').get(id);if(!r)return null;try{return JSON.parse(r.json)}catch(e){return null}});
ipcMain.handle("db:saveObject",(_,id,d)=>{if(!id)return false;const name=d.object||d.objectName||'Без названия';db.prepare("UPDATE objects SET name=?,json=?,updated=datetime('now') WHERE id=?").run(name,JSON.stringify(d),id);return true});
ipcMain.handle("db:deleteObject",(_,id)=>{db.prepare('DELETE FROM objects WHERE id=?').run(id);return true});
ipcMain.handle("db:dailyReports",(_,objectId)=>db.prepare('SELECT id,object_id objectId,report_date reportDate,updated FROM daily_reports WHERE object_id=? ORDER BY report_date DESC,id DESC').all(objectId));
ipcMain.handle("db:createDailyReport",(_,objectId,date)=>{const day=String(date||new Date().toISOString().slice(0,10));const found=db.prepare('SELECT id FROM daily_reports WHERE object_id=? AND report_date=?').get(objectId,day);if(found)return found.id;const d={reportDate:day,weather:{temp:'',wind:'',precip:''},workDays:[],invoices:[],workers:[],responsibles:[],equipment:[],actedDays:[],penalties:[],reportPhotos:[],reportSections:{}};const r=db.prepare("INSERT INTO daily_reports(object_id,report_date,json,updated) VALUES(?,?,?,datetime('now'))").run(objectId,day,JSON.stringify(d));return Number(r.lastInsertRowid)});
ipcMain.handle("db:loadDailyReport",(_,id)=>{const r=db.prepare('SELECT json FROM daily_reports WHERE id=?').get(id);if(!r)return null;try{return JSON.parse(r.json)}catch(e){return null}});
ipcMain.handle("db:saveDailyReport",(_,id,d)=>{if(!id)return false;const day=d.reportDate||new Date().toISOString().slice(0,10);db.prepare("UPDATE daily_reports SET report_date=?,json=?,updated=datetime('now') WHERE id=?").run(day,JSON.stringify(d),id);return true});
ipcMain.handle("db:deleteDailyReport",(_,id)=>{db.prepare('DELETE FROM daily_reports WHERE id=?').run(id);return true});
ipcMain.handle("db:objectAnalytics",(_,companyId)=>db.prepare('SELECT o.id,o.name,o.json object_json,d.report_date,d.json report_json FROM objects o LEFT JOIN daily_reports d ON d.object_id=o.id WHERE o.company_id=? ORDER BY o.id,d.report_date').all(companyId).map(r=>{try{return {...r,objectData:JSON.parse(r.object_json||'{}'),reportData:r.report_json?JSON.parse(r.report_json):null}}catch(e){return {...r,objectData:null,reportData:null}}}));

ipcMain.handle("file:objectPhoto",async()=>{const r=await dialog.showOpenDialog(win,{properties:["openFile"],filters:[{name:"Фото объекта",extensions:["png","jpg","jpeg","webp"]}]});if(r.canceled)return null;const p=r.filePaths[0],ext=path.extname(p).toLowerCase(),mime=ext===".png"?"image/png":ext===".webp"?"image/webp":"image/jpeg";return "data:"+mime+";base64,"+fs.readFileSync(p).toString("base64")});
