const {contextBridge,ipcRenderer}=require("electron");
// v8.0.210: exact persistence mirror. The relational database remains available for
// indexes/analytics, but every application value is also stored byte-for-byte in KV.
// Reads prefer this exact mirror, so object edits, reports, BOM and embedded photo data
// cannot be reconstructed from a stale/incomplete relational projection.
const dbWriteCache=new Map(),dbPendingWrites=new Map();
const EXACT_PREFIX="atemir_exact_v210__";
const exactKey=key=>EXACT_PREFIX+String(key);
const cloneDbValue=v=>{try{return structuredClone(v)}catch(e){try{return JSON.parse(JSON.stringify(v))}catch(_){return v}}};
const dbSetConsistent=(key,value)=>{const snapshot=cloneDbValue(value);dbWriteCache.set(key,snapshot);const previous=dbPendingWrites.get(key)||Promise.resolve();const p=previous.catch(()=>{}).then(async()=>{await ipcRenderer.invoke("db:set",key,snapshot);await ipcRenderer.invoke("db:set",exactKey(key),snapshot);const check=await ipcRenderer.invoke("db:get",exactKey(key));if(JSON.stringify(check)!==JSON.stringify(snapshot))throw Error("Persistence verification failed for "+key);return true}).then(r=>{if(dbPendingWrites.get(key)===p)dbPendingWrites.delete(key);return r},e=>{if(dbPendingWrites.get(key)===p){dbPendingWrites.delete(key);dbWriteCache.delete(key)}throw e});dbPendingWrites.set(key,p);return p};
const dbGetConsistent=async key=>{const pending=dbPendingWrites.get(key);if(pending)await pending;if(dbWriteCache.has(key))return cloneDbValue(dbWriteCache.get(key));let v=await ipcRenderer.invoke("db:get",exactKey(key));if(v===undefined||v===null)v=await ipcRenderer.invoke("db:get",key);dbWriteCache.set(key,cloneDbValue(v));return v};
const dbGetSyncConsistent=key=>{if(dbWriteCache.has(key))return cloneDbValue(dbWriteCache.get(key));let v=ipcRenderer.sendSync("db:get-sync",exactKey(key));if(v===undefined||v===null)v=ipcRenderer.sendSync("db:get-sync",key);dbWriteCache.set(key,cloneDbValue(v));return v};
const waitForDbWrites=async()=>{const pending=[...new Set(dbPendingWrites.values())];if(pending.length)await Promise.all(pending)};
const dbWriteManyConsistent=async(entries={})=>{const src=entries||{},mirrors={};for(const [k,v] of Object.entries(src)){dbWriteCache.set(k,cloneDbValue(v));mirrors[exactKey(k)]=cloneDbValue(v)}await ipcRenderer.invoke("db:write-many",src);await ipcRenderer.invoke("db:write-many",mirrors);return true};
const dbRemovePrefixConsistent=async(prefix)=>{prefix=String(prefix);for(const k of [...dbWriteCache.keys()])if(String(k).startsWith(prefix))dbWriteCache.delete(k);for(const k of [...dbPendingWrites.keys()])if(String(k).startsWith(prefix))dbPendingWrites.delete(k);await ipcRenderer.invoke("db:remove-prefix",prefix);await ipcRenderer.invoke("db:remove-prefix",EXACT_PREFIX+prefix);return true};
contextBridge.exposeInMainWorld("atemirDesktop",{dbGet:dbGetConsistent,dbGetSync:dbGetSyncConsistent,dbGetPrefixSync:(prefix)=>ipcRenderer.sendSync("db:get-prefix-sync",prefix),dbSet:dbSetConsistent,dbWaitForWrites:waitForDbWrites,dbRemove:async(key)=>{dbWriteCache.delete(key);dbPendingWrites.delete(key);await ipcRenderer.invoke("db:remove",key);await ipcRenderer.invoke("db:remove",exactKey(key));return true},dbInfo:()=>ipcRenderer.invoke("db:info"),dbBackup:()=>ipcRenderer.invoke("db:backup"),dbBackupFolder:()=>ipcRenderer.invoke("db:backup-folder"),dbRestore:()=>ipcRenderer.invoke("db:restore"),dbWriteMany:dbWriteManyConsistent,dbRemovePrefix:dbRemovePrefixConsistent,dbRemoveMany:(keys)=>ipcRenderer.invoke("db:remove-many",keys),dbDeleteObject:(id)=>ipcRenderer.invoke("db:delete-object",id),photoGet:(key)=>ipcRenderer.invoke("photos:get",key),photoSet:async(key,items)=>{const r=await ipcRenderer.invoke("photos:set",key,items);if(!r?.ok||Number(r.count)!==(Array.isArray(items)?items.length:0))throw Error("Не все фотографии сохранены");return r},photoRemove:(key)=>ipcRenderer.invoke("photos:remove",key),photoRemovePrefix:(prefix)=>ipcRenderer.invoke("photos:remove-prefix",prefix),savePdf:(arg)=>ipcRenderer.invoke("report:pdf",arg),saveHtml:(arg)=>ipcRenderer.invoke("report:html",arg),getVersion:()=>ipcRenderer.invoke("app:version"),checkUpdates:()=>ipcRenderer.invoke("app:update-check")});
function versionBadge(){ipcRenderer.invoke("app:version").then(v=>{let x=document.createElement("div");x.textContent="Версия "+v;x.title="Текущая версия программы";x.style.cssText="position:fixed;right:18px;bottom:18px;z-index:2147483000;padding:5px 9px;border-radius:7px;background:rgba(16,59,100,.08);color:#65798a;font:12px Arial,sans-serif;pointer-events:none";document.body.appendChild(x)}).catch(()=>{})}
function updaterUi(){versionBadge();
 let box=document.createElement("div");box.id="atemirUpdater";box.style.cssText="display:none;position:fixed;right:18px;bottom:18px;z-index:2147483647;width:min(430px,calc(100vw - 36px));background:#fff;border:1px solid #d8e2ea;border-radius:14px;padding:14px 16px;box-shadow:0 12px 36px rgba(0,0,0,.22);font:14px Arial,sans-serif;color:#173b59";
 box.innerHTML='<div style="display:flex;align-items:center;gap:10px"><div aria-hidden="true" style="width:38px;height:38px;flex:0 0 38px;border-radius:10px;background:#eef8fc;color:#168dca;display:flex;align-items:center;justify-content:center"><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v11"/><path d="m8 10 4 4 4-4"/><path d="M5 18v2h14v-2"/></svg></div><div style="flex:1"><b id="atemirUpdateTitle">Обновление программы</b><div id="atemirUpdateText" style="margin-top:4px;color:#667788"></div></div></div><div id="atemirUpdateTrack" style="display:none;height:8px;background:#e7edf2;border-radius:8px;overflow:hidden;margin-top:11px"><div id="atemirUpdateBar" style="height:100%;width:0;background:#e9a91b;transition:width .2s"></div></div><div id="atemirUpdateActions" style="display:none;gap:8px;margin-top:12px"><button id="atemirUpdateLater" style="flex:1;border:1px solid #d8e2ea;border-radius:8px;padding:10px 12px;background:#fff;color:#173b59;font-weight:700;cursor:pointer">Не сейчас</button><button id="atemirUpdateDownload" style="flex:1;border:0;border-radius:8px;padding:10px 12px;background:#123f66;color:white;font-weight:700;cursor:pointer">Да, скачать</button></div><button id="atemirUpdateRestart" style="display:none!important;margin-top:12px;width:100%;border:0;border-radius:8px;padding:10px 12px;background:#123f66;color:white;font-weight:700;cursor:pointer">Установить и перезапустить</button>';
 document.body.appendChild(box);let actions=box.querySelector("#atemirUpdateActions"),download=box.querySelector("#atemirUpdateDownload"),later=box.querySelector("#atemirUpdateLater");box.querySelector("#atemirUpdateRestart").onclick=()=>{let b=box.querySelector("#atemirUpdateRestart");b.disabled=true;b.textContent="Устанавливаем…";ipcRenderer.send("app:update-install")};download.onclick=()=>{actions.style.display="none";ipcRenderer.send("app:update-download")};later.onclick=()=>box.style.display="none";
 ipcRenderer.on("app:update",(_e,x)=>{let title=box.querySelector("#atemirUpdateTitle"),txt=box.querySelector("#atemirUpdateText"),track=box.querySelector("#atemirUpdateTrack"),bar=box.querySelector("#atemirUpdateBar"),btn=box.querySelector("#atemirUpdateRestart"),actions=box.querySelector("#atemirUpdateActions");
  if(x.state==="checking"){box.style.display="block";title.textContent="Проверяем обновления";txt.textContent="Проверяем наличие новой версии…";track.style.display="none";actions.style.display="none";btn.style.display="none";return}if(x.state==="none"){box.style.display="block";title.textContent="Обновлений нет";txt.textContent="У вас установлена актуальная версия"+(x.version?" "+x.version:"")+".";track.style.display="none";actions.style.display="none";btn.style.display="none";return}
  box.style.display="block";
  if(x.state==="available"){title.textContent="Есть обновление до версии "+x.version;txt.textContent=x.light?"Доступно небольшое обновление программы. Скачать сейчас?":"Скачать обновление сейчас? Программу можно продолжать использовать.";track.style.display="none";btn.style.display="none";actions.style.display="flex"}
  if(x.state==="downloading"){actions.style.display="none";title.textContent="Скачиваем обновление";txt.textContent=x.got+" МБ из "+x.total+" МБ — "+x.percent+"%";track.style.display="block";bar.style.width=x.percent+"%";btn.style.display="none"}
  if(x.state==="ready"){actions.style.display="none";title.textContent="Обновление "+x.version+" скачано";txt.textContent=x.light?"Небольшое обновление скачано. Нажмите «Установить и перезапустить».":"Обновление скачано. Сейчас программа установит его автоматически.";track.style.display="block";bar.style.width="100%";btn.style.setProperty("display",x.light?"block":"none","important")}
  if(x.state==="installing"){actions.style.display="none";title.textContent="Программа обновляется";txt.textContent="Пожалуйста, подождите. Программа установит обновление и автоматически перезапустится.";track.style.display="block";bar.style.width="100%";btn.style.display="none"}
  if(x.state==="error"){title.textContent="Не удалось проверить обновление";txt.textContent="Программа продолжит работать. Проверим снова при следующем запуске.";track.style.display="none";btn.style.display="none";setTimeout(()=>box.style.display="none",6000)}
 });
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",updaterUi);else updaterUi();
function navigationWriteBarrier207(){document.addEventListener("click",async e=>{const card=e.target?.closest?.("[data-id]");if(!card||e.target?.closest?.("button"))return;if(!location.pathname.endsWith("index.html")&&!location.pathname.endsWith("/"))return;if(!dbPendingWrites.size)return;e.preventDefault();e.stopImmediatePropagation();const id=card.dataset.id;try{await waitForDbWrites();location.href="object.html?object="+encodeURIComponent(id)}catch(err){console.error("Object save before navigation",err);alert("Не удалось завершить сохранение объекта. Откройте объект ещё раз после повторного сохранения.")}},true)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",navigationWriteBarrier207);else navigationWriteBarrier207();
function databaseUi143(){document.addEventListener("keydown",async e=>{if(e.ctrlKey&&e.shiftKey&&String(e.key).toLowerCase()==="b"){e.preventDefault();try{let x=await window.atemirDesktop.dbBackup();alert("Резервная копия базы создана:\n"+x.path)}catch(err){alert("Не удалось создать резервную копию базы.")}}});window.atemirDesktop.dbInfo().then(x=>console.info("A-Temir local database",x)).catch(()=>{})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",databaseUi143);else databaseUi143();
