const views=[["home","Отчёт"],["progress","Сводка объёмов"],["works","Выполненные работы"],["bom","Ведомость марок"],["invoices","Поставка"],["people","Ответственные / работники"],["machines","Машины и механизмы"],["deadlines","Сроки выполнения"],["acted","Актированные дни"],["penalties","Штрафы"],["manage","Меню управления"]];
let state={object:"",address:"",client:"",reportDate:"",weather:{},tasks:[],workDays:[],invoices:[],workers:[],responsibles:[],equipment:[],deadlines:[],actedDays:[],penalties:[],reportPhotos:[]},view="home";
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const arr=n=>Array.isArray(state[n])?state[n]:[];
const card=(t,b)=>`<div class="card"><h2>${t}</h2><div class="body">${b}</div></div>`;
function table(rows,cols){if(!rows.length)return '<div class="empty">Нет данных</div>';return '<table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(typeof c[1]==="function"?c[1](r):r[c[1]])+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
async function save(){await ATEmir.save(state)}
function summary(){return card("Сводка объёмов работ",table(arr("tasks").map(t=>{const done=arr("workDays").filter(w=>(w.type||"")===(t.type||"")&&(w.code||"")===(t.code||"")).reduce((a,w)=>a+(+w.qty||+w.quantity||0),0),p=+t.qty||+t.quantity||+t.volume||0;return{type:t.type,code:t.code,p,done,left:Math.max(0,p-done),unit:t.unit}}),[["Работа","type"],["Шифр","code"],["Проект","p"],["Выполнено","done"],["Остаток","left"],["Ед.","unit"]]))}
function home(){return card("Дата отчёта",esc(state.reportDate||"—"))+summary()+card("Выполненные работы",table(arr("workDays").slice(-20),[["Дата","date"],["Работа","type"],["Шифр","code"],["Марка","mark"],["Количество",r=>r.qty||r.quantity],["Ед.","unit"]]))}
function manage(){return card("Объект",`<div class="grid"><div class="field"><label>Наименование объекта</label><textarea data-f="object">${esc(state.object||state.objectName||"")}</textarea></div><div class="field"><label>Адрес</label><textarea data-f="address">${esc(state.address)}</textarea></div><div class="field"><label>Заказчик</label><textarea data-f="client">${esc(state.client||state.customer||"")}</textarea></div><div class="field"><label>Дата отчёта</label><input type="date" data-f="reportDate" value="${esc(state.reportDate)}"></div></div>`)}
function render(){document.querySelector("#nav").innerHTML=views.map(x=>`<button data-v="${x[0]}" class="${view===x[0]?"active":""}">${x[1]}</button>`).join("");document.querySelector("#title").textContent=views.find(x=>x[0]===view)[1];document.querySelector("#obj").textContent=state.object||state.objectName||"Новый объект";const c=document.querySelector("#content");
if(view==="home")c.innerHTML=home();else if(view==="progress")c.innerHTML=summary();else if(view==="works")c.innerHTML=card("Выполненные работы",table(arr("workDays"),[["Дата","date"],["Работа","type"],["Шифр","code"],["Марка","mark"],["Наименование","name"],["Количество",r=>r.qty||r.quantity],["Ед.","unit"]]));else if(view==="bom")c.innerHTML=card("Ведомость марок",table(arr("tasks").flatMap(t=>(t.bom||[]).map(b=>({...b,type:t.type,code:t.code}))),[["Работа","type"],["Шифр","code"],["Марка","mark"],["Наименование","name"],["Количество",r=>r.qty||r.quantity]]));else if(view==="invoices")c.innerHTML=card("Поставка",table(arr("invoices"),[["Дата","date"],["Шифр","code"],["Марка","mark"],["Количество",r=>r.qty||r.quantity]]));else if(view==="people")c.innerHTML=card("Ответственные / работники",table([...arr("responsibles"),...arr("workers")],[["ФИО",r=>r.name||r.fio],["Должность","position"]]));else if(view==="machines")c.innerHTML=card("Машины и механизмы",table(arr("equipment"),[["Наименование",r=>r.name||r.title],["Количество",r=>r.qty||r.quantity]]));else if(view==="deadlines")c.innerHTML=card("Сроки выполнения",table(arr("deadlines"),[["Работа","type"],["Шифр","code"],["Начало","start"],["Окончание",r=>r.end||r.date]]));else if(view==="acted")c.innerHTML=card("Актированные дни",table(arr("actedDays"),[["Дата",r=>r.date||r]]));else if(view==="penalties")c.innerHTML=card("Штрафы",table(arr("penalties"),[["Дата","date"],["Описание",r=>r.text||r.reason||r.name],["Сумма","amount"]]));else c.innerHTML=manage();
c.oninput=async e=>{if(e.target.dataset.f){state[e.target.dataset.f]=e.target.value;await save();document.querySelector("#obj").textContent=state.object||"Новый объект"}}}
document.querySelector("#nav").onclick=e=>{const b=e.target.closest("[data-v]");if(b){view=b.dataset.v;render()}};
document.querySelector("#imp").onclick=async()=>{try{const d=await ATEmir.importJSON();if(d){state={...state,...d};await save();render();alert("SaveFiles импортирован.")}}catch(e){alert(e.message)}};
document.querySelector("#bak").onclick=()=>ATEmir.backup(state);document.querySelector("#pdf").onclick=()=>ATEmir.pdf();document.querySelector("#html").onclick=()=>{const title=esc(state.object||"Отчёт");ATEmir.exportHTML(`<!doctype html><html lang="ru"><meta charset="utf-8"><title>${title}</title><style>body{font-family:Arial;margin:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:6px}</style><body><h1>${title}</h1>${home()}</body></html>`)};
(async()=>{const d=await ATEmir.load();if(d)state=d;render()})().catch(e=>alert("Ошибка запуска: "+e.message));