const views=[["home","Отчёт"],["progress","Сводка объёмов"],["works","Выполненные работы"],["bom","Ведомость марок"],["invoices","Поставка"],["people","Ответственные / работники"],["machines","Машины и механизмы"],["deadlines","Сроки выполнения"],["acted","Актированные дни"],["penalties","Штрафы"],["manage","Меню управления"]];
const manageViews=[["object","Объект"],["types","Виды работ"],["tasks","Задачи / ведомость"],["reportInfo","Дата, погода, фото"],["deadlines","Сроки выполнения"],["works","Выполненные работы"],["invoices","Поставка"],["workers","Работники"],["responsibles","Ответственные"],["equipment","Машины и механизмы"],["acted","Актированные дни"],["penalties","Штрафы"]];
let state={object:"",address:"",client:"",reportDate:"",weather:{temp:"",wind:"",precip:""},workTypes:[],tasks:[],workDays:[],invoices:[],workers:[],responsibles:[],equipment:[],deadlines:[],actedDays:[],penalties:[],reportPhotos:[],companyLogo:""},view="home",manageView="object";
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const arr=n=>Array.isArray(state[n])?state[n]:[], card=(t,b)=>`<div class="card"><h2>${t}</h2><div class="body">${b}</div></div>`;
let saveTimer=null,saveBusy=false,saveAgain=false;
async function flushSave(){
 if(saveBusy){saveAgain=true;return}
 saveBusy=true;
 try{await ATemir.save(state)}finally{
  saveBusy=false;
  if(saveAgain){saveAgain=false;await flushSave()}
 }
}
function save(immediate=false){
 clearTimeout(saveTimer);
 if(immediate)return flushSave();
 saveTimer=setTimeout(flushSave,450);
}
function table(rows,cols){if(!rows.length)return '<div class="empty">Нет данных</div>';return '<table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(typeof c[1]==="function"?c[1](r):r[c[1]])+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function fieldEditor(key,r,i,f){
 const [label,k,type]=f, val=r[k]??"";
 if(type==="worktype"){
  const opts=arr("workTypes").map(x=>x.name).filter(Boolean);
  const all=(val&&!opts.includes(val))?[val,...opts]:opts;
  return `<div class="field"><label>${label}</label><select data-list="${key}" data-i="${i}" data-k="${k}"><option value="">Выберите вид работ</option>${all.map(x=>`<option value="${esc(x)}" ${x===val?"selected":""}>${esc(x)}</option>`).join("")}</select></div>`;
 }
 return `<div class="field"><label>${label}</label><input data-list="${key}" data-i="${i}" data-k="${k}" type="${type||"text"}" value="${esc(val)}"></div>`;
}
function rowEditor(key,fields){const rows=arr(key);return `<div class="editorRows">${rows.map((r,i)=>`<div class="editRow">${fields.map(f=>fieldEditor(key,r,i,f)).join("")}<button class="danger" data-del="${key}" data-i="${i}">Удалить</button></div>`).join("")}</div><button class="btn add" data-add="${key}">+ Добавить</button>`}
function summary(){const rows=arr("tasks").map(t=>{const done=arr("workDays").filter(w=>(w.type||"")===(t.type||"")&&(w.code||"")===(t.code||"")).reduce((a,w)=>a+(+w.qty||+w.quantity||0),0),del=arr("invoices").filter(i=>(!i.type||i.type===t.type)&&(i.code||"")===(t.code||"")).reduce((a,i)=>a+(+i.qty||+i.quantity||0),0),p=+t.qty||+t.quantity||+t.volume||0;return{type:t.type,code:t.code,p,del,done,left:Math.max(0,p-done),unit:t.unit}});return card("Сводка объёмов работ",table(rows,[["Работа","type"],["Шифр","code"],["Проект","p"],["Поставлено","del"],["Выполнено","done"],["Остаток","left"],["Ед.","unit"]]))}
function home(){return (state.companyLogo?`<div class="reportLogo"><img src="${state.companyLogo}" alt="Логотип компании"></div>`:"")+card("Дата отчёта",`<b>${esc(state.reportDate||"—")}</b> &nbsp; Температура: ${esc(state.weather?.temp||"—")} °C &nbsp; Ветер: ${esc(state.weather?.wind||"—")} м/с &nbsp; Осадки: ${esc(state.weather?.precip||"—")}`)+summary()+card("Ответственные лица",table(arr("responsibles"),[["ФИО",r=>r.name||r.fio],["Должность","position"]]))+card("Работники",table(arr("workers"),[["ФИО",r=>r.name||r.fio],["Должность","position"]]))+card("Машины и механизмы",table(arr("equipment"),[["Наименование",r=>r.name||r.title],["Количество",r=>r.qty||r.quantity]]))+card("Выполненные работы",table(arr("workDays").slice(-20),[["Дата","date"],["Работа","type"],["Шифр","code"],["Марка","mark"],["Количество",r=>r.qty||r.quantity],["Ед.","unit"]]))}
function management(){
 let b=`<div class="manageTabs">${manageViews.map(x=>`<button data-mv="${x[0]}" class="${manageView===x[0]?"active":""}">${x[1]}</button>`).join("")}</div>`;
 if(manageView==="object") b+=card("Логотип компании",`<div class="logoEditor">${state.companyLogo?`<img src="${state.companyLogo}" alt="Логотип">`:`<div class="logoEmpty">Логотип не загружен</div>`}<div><button class="btn" data-logo-load>Загрузить логотип</button>${state.companyLogo?`<button class="danger logoRemove" data-logo-remove>Удалить</button>`:""}<p class="hint">PNG, JPG/JPEG или WebP. Логотип сохраняется вместе с базой и резервной копией.</p></div></div>`)+card("Объект",`<div class="grid"><div class="field"><label>Наименование объекта</label><textarea data-root="object">${esc(state.object||state.objectName||"")}</textarea></div><div class="field"><label>Адрес</label><textarea data-root="address">${esc(state.address)}</textarea></div><div class="field"><label>Заказчик</label><textarea data-root="client">${esc(state.client||state.customer||"")}</textarea></div></div>`);
 if(manageView==="types") b+=card("Виды работ",rowEditor("workTypes",[["Наименование","name"]]));
 if(manageView==="tasks") b+=card("Задачи — объёмы согласно проекту",rowEditor("tasks",[["Вид работ","type","worktype"],["Шифр проекта","code"],["Проектный объём","qty","number"],["Ед.","unit"]])+'<p class="hint">Импорт Excel-ведомости марок будет следующим модулем. Уже импортированные из старого SaveFiles BOM сохраняются.</p>');
 if(manageView==="reportInfo") b+=card("Дата отчёта и погода",`<div class="grid"><div class="field"><label>Дата</label><input type="date" data-root="reportDate" value="${esc(state.reportDate)}"></div><div class="field"><label>Температура °C</label><input data-weather="temp" value="${esc(state.weather?.temp)}"></div><div class="field"><label>Ветер м/с</label><input data-weather="wind" value="${esc(state.weather?.wind)}"></div><div class="field"><label>Осадки</label><input data-weather="precip" value="${esc(state.weather?.precip)}"></div></div><p class="hint">Фото из старого SaveFiles сохраняются. Новый загрузчик фото добавим отдельным модулем.</p>`);
 const configs={deadlines:[["Работа","type","worktype"],["Шифр","code"],["Начало","start","date"],["Окончание","end","date"]],works:[["Дата","date","date"],["Работа","type","worktype"],["Шифр","code"],["Марка","mark"],["Наименование","name"],["Количество","qty","number"],["Ед.","unit"]],invoices:[["Дата","date","date"],["Работа","type","worktype"],["Шифр","code"],["Марка","mark"],["Количество","qty","number"]],workers:[["ФИО","name"],["Должность","position"]],responsibles:[["ФИО","name"],["Должность","position"]],equipment:[["Наименование","name"],["Количество","qty","number"]],acted:[["Дата","date","date"]],penalties:[["Дата","date","date"],["Описание","text"],["Сумма","amount","number"]]};
 const keys={deadlines:"deadlines",works:"workDays",invoices:"invoices",workers:"workers",responsibles:"responsibles",equipment:"equipment",acted:"actedDays",penalties:"penalties"};
 if(configs[manageView]) b+=card(manageViews.find(x=>x[0]===manageView)[1],rowEditor(keys[manageView],configs[manageView]));
 return b;
}
function render(){$("#nav").innerHTML=views.map(x=>`<button data-v="${x[0]}" class="${view===x[0]?"active":""}">${x[1]}</button>`).join("");$("#title").textContent=views.find(x=>x[0]===view)?.[1]||"Отчёт";$("#obj").textContent=state.object||state.objectName||"Новый объект";const c=$("#content");
 if(view==="home")c.innerHTML=home();else if(view==="progress")c.innerHTML=summary();else if(view==="works")c.innerHTML=card("Выполненные работы",table(arr("workDays"),[["Дата","date"],["Работа","type"],["Шифр","code"],["Марка","mark"],["Наименование","name"],["Количество",r=>r.qty||r.quantity],["Ед.","unit"]]));else if(view==="bom")c.innerHTML=card("Ведомость марок",table(arr("tasks").flatMap(t=>(t.bom||[]).map(b=>({...b,type:t.type,code:t.code}))),[["Работа","type"],["Шифр","code"],["Марка","mark"],["Наименование","name"],["Количество",r=>r.qty||r.quantity],["Вес 1 ед.",r=>r.weight1||r.weight]]));else if(view==="invoices")c.innerHTML=card("Поставка",table(arr("invoices"),[["Дата","date"],["Работа","type"],["Шифр","code"],["Марка","mark"],["Количество",r=>r.qty||r.quantity]]));else if(view==="people")c.innerHTML=card("Ответственные / работники",table([...arr("responsibles"),...arr("workers")],[["ФИО",r=>r.name||r.fio],["Должность","position"]]));else if(view==="machines")c.innerHTML=card("Машины и механизмы",table(arr("equipment"),[["Наименование",r=>r.name||r.title],["Количество",r=>r.qty||r.quantity]]));else if(view==="deadlines")c.innerHTML=card("Сроки выполнения",table(arr("deadlines"),[["Работа","type"],["Шифр","code"],["Начало","start"],["Окончание",r=>r.end||r.date]]));else if(view==="acted")c.innerHTML=card("Актированные дни",table(arr("actedDays"),[["Дата",r=>r.date||r]]));else if(view==="penalties")c.innerHTML=card("Штрафы",table(arr("penalties"),[["Дата","date"],["Описание",r=>r.text||r.reason||r.name],["Сумма","amount"]]));else c.innerHTML=management();
}
$("#nav").onclick=e=>{const b=e.target.closest("[data-v]");if(b){view=b.dataset.v;render()}};
$("#content").onclick=async e=>{const ll=e.target.closest("[data-logo-load]");if(ll){const data=await ATemir.chooseLogo();if(data){state.companyLogo=data;await save(true);render()}return}const lr=e.target.closest("[data-logo-remove]");if(lr){state.companyLogo="";await save(true);render();return}const m=e.target.closest("[data-mv]");if(m){manageView=m.dataset.mv;render();return}const a=e.target.closest("[data-add]");if(a){state[a.dataset.add]=arr(a.dataset.add);state[a.dataset.add].push({});await save(true);render();return}const d=e.target.closest("[data-del]");if(d){arr(d.dataset.del).splice(+d.dataset.i,1);await save(true);render()}};
$("#content").oninput=async e=>{if(e.target.dataset.root){state[e.target.dataset.root]=e.target.value}else if(e.target.dataset.weather){state.weather=state.weather||{};state.weather[e.target.dataset.weather]=e.target.value}else if(e.target.dataset.list){const r=arr(e.target.dataset.list)[+e.target.dataset.i];r[e.target.dataset.k]=e.target.value}save();$("#obj").textContent=state.object||"Новый объект"};
$("#imp").onclick=async()=>{try{const d=await ATemir.importJSON();if(d){state={...state,...d};state.weather=state.weather||{};await save(true);render();alert("SaveFiles импортирован и сохранён в SQLite.")}}catch(e){alert("Ошибка импорта: "+e.message)}};$("#bak").onclick=()=>ATemir.backup(state);$("#pdf").onclick=()=>ATemir.pdf();$("#html").onclick=()=>{const title=esc(state.object||"Отчёт");ATemir.exportHTML(`<!doctype html><html lang="ru"><meta charset="utf-8"><title>${title}</title><style>body{font-family:Arial;margin:20px;color:#183247}.card{margin-bottom:15px}.card h2{border-bottom:2px solid #f2b318}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:6px}</style><body><h1>${title}</h1>${home()}</body></html>`)};
(async()=>{const d=await ATemir.load();if(d)state={...state,...d};state.weather=state.weather||{};render()})().catch(e=>alert("Ошибка запуска: "+e.message));
window.addEventListener("blur",()=>flushSave());
window.addEventListener("beforeunload",()=>{try{flushSave()}catch(e){}});

$("#content").onchange=async e=>{if(e.target.dataset.list){const r=arr(e.target.dataset.list)[+e.target.dataset.i];if(r){r[e.target.dataset.k]=e.target.value;await save(true)}}};
