(()=>{"use strict";
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const id=new URLSearchParams(location.search).get("object")||"default",objects=JSON.parse(localStorage.getItem("atemir-company-objects-v1")||"[]"),obj=objects.find(x=>String(x.id)===String(id))||{name:"Объект",address:"",client:""};
const key="atemir_v9__object_"+id,blank=()=>({version:72,base:{objectName:obj.name||"",address:obj.address||"",client:obj.client||""},reportDate:"",weather:{location:"",temp:"",wind:"",precip:""},reportPhotos:[],actedDays:[],penalties:[],workTypes:[],tasks:[],deadlines:[],workDays:[],invoices:[],workers:[],responsibles:[{role:"",fio:"",collapsed:false}],equipment:[]});
let d;try{d=Object.assign(blank(),JSON.parse(localStorage.getItem(key)||"{}"))}catch{d=blank()}let active="home",timer;
const sections=[["home","Сводка"],["scheme","Монтажная схема"],["bom","Ведомость / марки"],["dynamics","Динамика"],["works","Выполненные работы"],["invoices","Поставки / накладные"],["tasks","Проект / объёмы"],["deadlines","Сроки"],["acted","Актированные дни"],["workers","Рабочие"],["responsibles","Ответственные"],["equipment","Техника"],["penalties","Штрафы"],["photos","Фотоотчёт"]];
function save(){clearTimeout(timer);$("#saveState").textContent="Сохраняю…";timer=setTimeout(()=>{localStorage.setItem(key,JSON.stringify({...d,reportPhotos:[]}));$("#saveState").textContent="Сохранено"},250)}
function field(label,path,type="text"){let v=path.reduce((o,k)=>o?.[k],d)??"";return '<div><label>'+label+'</label><input data-field="'+path.join(".")+'" type="'+type+'" value="'+esc(v)+'"></div>'}
function card(title,body){return '<div class="card"><h2>'+title+'</h2>'+body+'</div>'}
function rows(name,title,fields,maker){let arr=d[name]||[],h='<div class="toolbar"><button class="primary" data-add="'+name+'">+ Добавить</button></div>';if(!arr.length)return h+'<div class="empty">Пока нет данных</div>';arr.forEach((x,i)=>{h+='<div class="card"><div class="rowhead"><b>'+title+' '+(i+1)+'</b><button class="danger" data-del="'+name+':'+i+'">Удалить</button></div><div class="grid g3">';fields.forEach(f=>{h+='<div><label>'+f[0]+'</label><input data-item="'+name+':'+i+':'+f[1]+'" type="'+(f[2]||"text")+'" value="'+esc(x[f[1]]??"")+'"></div>'});h+='</div></div>'});return h}
const makers={tasks:()=>({type:"",code:"",volume:"",unit:"",bom:[],bomName:""}),deadlines:()=>({type:"",code:"",start:"",date:""}),actedDays:()=>({date:"",reason:"Ветер",value:"",from:"",to:""}),workers:()=>({name:"",qty:1}),responsibles:()=>({role:"",fio:""}),equipment:()=>({type:"Автокран 25 т",custom:"",qty:1}),penalties:()=>({date:"",amount:"",responsible:"",reason:""}),invoices:()=>({date:"",no:"",items:[]}),workDays:()=>({date:"",items:[]})};
async function unzipXlsx(buf){let u=new Uint8Array(buf),dv=new DataView(buf),sig=0x06054b50,e=-1;for(let i=u.length-22;i>=Math.max(0,u.length-65557);i--)if(dv.getUint32(i,true)===sig){e=i;break}if(e<0)throw Error("ZIP");let count=dv.getUint16(e+10,true),off=dv.getUint32(e+16,true),files={};for(let k=0;k<count;k++){if(dv.getUint32(off,true)!==0x02014b50)break;let method=dv.getUint16(off+10,true),cs=dv.getUint32(off+20,true),nl=dv.getUint16(off+28,true),xl=dv.getUint16(off+30,true),cl=dv.getUint16(off+32,true),lo=dv.getUint32(off+42,true),name=new TextDecoder().decode(u.slice(off+46,off+46+nl)),ln=dv.getUint16(lo+26,true),le=dv.getUint16(lo+28,true),data=u.slice(lo+30+ln+le,lo+30+ln+le+cs);if(method===8){let ds=new DecompressionStream("deflate-raw"),ab=await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer();files[name]=new TextDecoder().decode(ab)}else if(method===0)files[name]=new TextDecoder().decode(data);off+=46+nl+xl+cl}return files}
function rowsToBom(rows){rows=(rows||[]).filter(r=>r.some(v=>String(v||"").trim()));let hi=rows.findIndex(r=>r.some(v=>/марка/i.test(String(v||""))));if(hi<0)hi=0;let h=rows[hi]||[],vals=h.map(v=>String(v||"").toLowerCase().replace(/ё/g,"е").replace(/\s+/g," ").trim()),find=names=>vals.findIndex(v=>names.some(n=>v.includes(n))),im=find(["марка"]),ina=find(["наименование"]),iq=find(["кол-во","количество","кол."]),iw=find(["вес 1","масса 1","вес ед","масса ед"]),it=find(["общий вес","масса всего","вес всего","всего, кг"]),num=v=>parseFloat(String(v??"").replace(/\s/g,"").replace(",","."))||0;return rows.slice(hi+1).map(r=>{let q=num(r[iq]),w=num(r[iw]),wt=num(r[it]);if(!q&&w&&wt)q=Math.round(wt/w*1000)/1000;if(!wt&&q&&w)wt=q*w;return{mark:String(r[im]||"").trim().toUpperCase().replace(/^K(?=\d)/,"К"),name:String(r[ina]||"").trim(),qty:q,weight1:w,weightTotal:wt}}).filter(r=>r.mark)}
async function parseXlsx(file){let files=await unzipXlsx(await file.arrayBuffer()),ss=[];if(files["xl/sharedStrings.xml"]){let doc=new DOMParser().parseFromString(files["xl/sharedStrings.xml"],"application/xml");ss=[...doc.querySelectorAll("si")].map(si=>[...si.querySelectorAll("t")].map(t=>t.textContent).join(""))}let sheet=files["xl/worksheets/sheet1.xml"]||Object.entries(files).find(([k])=>/^xl\/worksheets\/sheet\d+\.xml$/.test(k))?.[1];if(!sheet)throw Error("SHEET");let doc=new DOMParser().parseFromString(sheet,"application/xml"),rows=[];[...doc.querySelectorAll("row")].forEach(row=>{let arr=[];[...row.querySelectorAll("c")].forEach(c=>{let ref=c.getAttribute("r")||"",col=(ref.match(/[A-Z]+/)||["A"])[0],ci=0;for(let ch of col)ci=ci*26+ch.charCodeAt(0)-64;ci--;let typ=c.getAttribute("t"),v=c.querySelector("v")?.textContent??"",val=typ==="s"?(ss[+v]??""):typ==="inlineStr"?(c.querySelector("is")?.textContent??""):v;arr[ci]=val});rows.push(arr)});return rowsToBom(rows)}
function render(){
 $("#objTitle").textContent=obj.name||"Объект";$("#pageTitle").textContent=sections.find(x=>x[0]===active)?.[1]||"Отчёт";$("#pageSub").textContent=(obj.name||"")+" · "+(obj.address||"");
 $("#nav").innerHTML=sections.map(x=>'<button data-v="'+x[0]+'" class="'+(x[0]===active?"on":"")+'">'+x[1]+'</button>').join("");
 let h="";
 if(active==="home"){let workers=d.workers.reduce((s,x)=>s+(Number(x.qty)||0),0),eq=d.equipment.reduce((s,x)=>s+(Number(x.qty)||0),0);h=card("Объект",'<div class="grid g3">'+field("Наименование",["base","objectName"])+field("Адрес",["base","address"])+field("Заказчик",["base","client"])+field("Дата отчёта",["reportDate"],"date")+field("Температура, °C",["weather","temp"],"number")+field("Ветер, м/с",["weather","wind"],"number")+'</div>')+card("Сводка",'<div class="stat"><div>Рабочих<b>'+workers+'</b></div><div>Техники<b>'+eq+'</b></div><div>Дней работ<b>'+d.workDays.length+'</b></div><div>Штрафов<b>'+d.penalties.length+'</b></div></div>')}
 else if(active==="tasks"){let body='<div class="toolbar"><button class="primary" data-add="tasks">+ Добавить</button></div>';if(!d.tasks.length)body+='<div class="empty">Пока нет проектных позиций</div>';d.tasks.forEach((t,i)=>{let bom=t.bom||[],qty=bom.reduce((s,r)=>s+(Number(r.qty)||0),0),wt=bom.reduce((s,r)=>s+(Number(r.weightTotal)||0),0);body+='<div class="card"><div class="rowhead"><b>Проектная позиция '+(i+1)+'</b><button class="danger" data-del="tasks:'+i+'">Удалить</button></div><div class="grid g3"><div><label>Вид работы</label><input data-item="tasks:'+i+':type" value="'+esc(t.type||"")+'"></div><div><label>Шифр</label><input data-item="tasks:'+i+':code" value="'+esc(t.code||"")+'"></div><div><label>Проектный объём</label><input type="number" data-item="tasks:'+i+':volume" value="'+esc(t.volume||"")+'"></div><div><label>Ед.</label><select data-item="tasks:'+i+':unit">'+["тн","м²","м³","кг","шт","м","компл."].map(u=>'<option'+(u===t.unit?' selected':'')+'>'+u+'</option>').join("")+'</select></div></div><div class="taskBom173"><div class="taskBomTop173"><b>Ведомость элементов</b><label class="primary small">Загрузить ведомость<input hidden data-bom="'+i+'" type="file" accept=".xlsx,.csv,.txt,text/csv"></label>'+(bom.length?'<button class="white small" data-bom-clear="'+i+'">Очистить</button>':'')+'</div><div class="taskBomHint173">CSV/TXT: <b>Марка | Наименование | Количество | Вес 1 ед. | Общий вес</b>.</div><div class="taskBomStatus173">'+(bom.length?esc(t.bomName||"Ведомость")+' · '+bom.length+' марок · '+qty+' шт. · '+wt.toFixed(2)+' кг':'Ведомость не загружена')+'</div></div></div>'});h=body;}
 else if(active==="deadlines")h=rows("deadlines","Срок",[["Вид работы","type"],["Шифр","code"],["Начало","start","date"],["Окончание","date","date"]]);
 else if(active==="acted")h=rows("actedDays","Актированный день",[["Дата","date","date"],["Причина","reason"],["Значение","value"],["С","from","time"],["До","to","time"]]);
 else if(active==="workers")h=rows("workers","Рабочие",[["Специальность / группа","name"],["Количество","qty","number"]]);
 else if(active==="responsibles")h=rows("responsibles","Ответственный",[["Должность","role"],["ФИО","fio"]]);
 else if(active==="equipment")h=rows("equipment","Машина / механизм",[["Тип","type"],["Другое","custom"],["Количество","qty","number"]]);
 else if(active==="penalties")h=rows("penalties","Штраф",[["Дата","date","date"],["Сумма","amount","number"],["Ответственный","responsible"],["Причина","reason"]]);
 else if(active==="works"){let body='<div class="toolbar"><button class="primary" data-add="workDays">+ Добавить день</button></div>';if(!d.workDays.length)body+='<div class="empty">Пока нет выполненных работ</div>';d.workDays.forEach((day,di)=>{day.items=day.items||[];body+='<div class="card"><div class="rowhead"><b>День работ '+(di+1)+'</b><button class="danger" data-del="workDays:'+di+'">Удалить день</button></div><div class="grid g3"><div><label>Дата</label><input type="date" data-item="workDays:'+di+':date" value="'+esc(day.date||"")+'"></div></div><div class="toolbar"><button class="primary" data-work-add="'+di+'">+ Добавить работу</button></div>';day.items.forEach((x,ii)=>{let task=d.tasks.find(t=>t.code===x.code&&(t.type===x.type||!x.type))||d.tasks.find(t=>t.code===x.code),bom=task?.bom||[],marks=bom.map(r=>'<option value="'+esc(r.mark)+'"'+(r.mark===x.mark?' selected':'')+'>'+esc(r.mark)+' — '+esc(r.name||"")+'</option>').join("");body+='<div class="card"><div class="rowhead"><b>Работа '+(ii+1)+'</b><button class="danger" data-work-del="'+di+':'+ii+'">Удалить</button></div><div class="grid g3"><div><label>Вид работы</label><input data-work="'+di+':'+ii+':type" value="'+esc(x.type||"")+'"></div><div><label>Шифр</label><select data-work="'+di+':'+ii+':code"><option value="">— выберите —</option>'+d.tasks.map(t=>'<option value="'+esc(t.code||"")+'"'+(t.code===x.code?' selected':'')+'>'+esc(t.code||"")+'</option>').join("")+'</select></div><div><label>Марка</label><select data-work="'+di+':'+ii+':mark"><option value="">— выберите —</option>'+marks+'</select></div><div><label>Наименование</label><input readonly value="'+esc(x.name||"")+'"></div><div><label>Ось</label><input data-work="'+di+':'+ii+':axis" value="'+esc(x.axis||"")+'"></div><div><label>Отметка</label><input data-work="'+di+':'+ii+':level" value="'+esc(x.level||"")+'"></div><div><label>Количество</label><input type="number" data-work="'+di+':'+ii+':qty" value="'+esc(x.qty||"")+'"></div><div><label>Ед.</label><input readonly value="'+esc(x.unit||task?.unit||"")+'"></div><div><label>Вес / коэф.</label><input readonly value="'+esc(x.per||"")+'"></div></div></div>'});body+='</div>'});h=body;}
 else if(active==="invoices"){let body='<div class="toolbar"><button class="primary" data-add="invoices">+ Добавить накладную</button></div>';if(!d.invoices.length)body+='<div class="empty">Пока нет поставок</div>';d.invoices.forEach((inv,di)=>{inv.items=inv.items||[];body+='<div class="card"><div class="rowhead"><b>Накладная '+(di+1)+'</b><button class="danger" data-del="invoices:'+di+'">Удалить</button></div><div class="grid g3"><div><label>Дата</label><input type="date" data-item="invoices:'+di+':date" value="'+esc(inv.date||"")+'"></div><div><label>Номер</label><input data-item="invoices:'+di+':no" value="'+esc(inv.no||inv.number||"")+'"></div></div><div class="toolbar"><button class="primary" data-inv-add="'+di+'">+ Добавить позицию</button></div>';inv.items.forEach((x,ii)=>{body+='<div class="card"><div class="rowhead"><b>Позиция '+(ii+1)+'</b><button class="danger" data-inv-del="'+di+':'+ii+'">Удалить</button></div><div class="grid g3"><div><label>Вид работы</label><input data-inv="'+di+':'+ii+':type" value="'+esc(x.type||"")+'"></div><div><label>Шифр</label><select data-inv="'+di+':'+ii+':code"><option value="">— выберите —</option>'+d.tasks.map(t=>'<option value="'+esc(t.code||"")+'"'+(t.code===x.code?' selected':'')+'>'+esc(t.code||"")+'</option>').join("")+'</select></div><div><label>Наименование</label><input data-inv="'+di+':'+ii+':name" value="'+esc(x.name||"")+'"></div><div><label>Марка</label><input data-inv="'+di+':'+ii+':mark" value="'+esc(x.mark||"")+'"></div><div><label>Количество</label><input type="number" data-inv="'+di+':'+ii+':qty" value="'+esc(x.qty||"")+'"></div><div><label>Ед.</label><input data-inv="'+di+':'+ii+':unit" value="'+esc(x.unit||"")+'"></div><div><label>Вес / коэф.</label><input type="number" data-inv="'+di+':'+ii+':per" value="'+esc(x.per||"")+'"></div></div></div>'});body+='</div>'});h=body;}
 else if(active==="bom"){let norm=v=>String(v||"").trim().toUpperCase().replace(/^K(?=\d)/,"К").replace(/\s+/g,""),num=v=>parseFloat(String(v??"").replace(",", "."))||0,used=(t,m)=>d.workDays.reduce((s,day)=>s+(day.items||[]).filter(x=>String(x.code||"")===String(t.code||"")&&(!x.type||!t.type||String(x.type)===String(t.type))&&norm(x.mark)===norm(m)).reduce((q,x)=>q+num(x.qty),0),0),all=[],mounted=0,total=0;d.tasks.forEach(t=>(t.bom||[]).forEach(r=>{let q=num(r.qty),done=Math.min(q,used(t,r.mark)),state=q>0&&done>=q?"done":done>0?"partial":"left";total+=q;mounted+=done;all.push({t,r,q,done,state})}));let pct=total?Math.round(mounted/total*100):0,body='<div class="stat"><div>Всего элементов<b>'+total+'</b></div><div>Смонтировано<b>'+mounted+'</b></div><div>Осталось<b>'+Math.max(0,total-mounted)+'</b></div><div>Готовность<b>'+pct+'%</b></div></div><div class="toolbar"><button class="white" data-bom-filter="all">Все</button><button class="white" data-bom-filter="done">Смонтировано</button><button class="white" data-bom-filter="left">Осталось</button></div><div id="bomRows">';if(!all.length)body+='<div class="empty">Загрузите ведомость в разделе «Проект / объёмы».</div>';all.forEach(x=>{body+='<div class="card bomrow '+x.state+'" data-state="'+x.state+'"><div class="rowhead"><b>'+esc(x.r.mark||"Без марки")+'</b><span>'+esc(x.t.code||"")+'</span></div><div>'+esc(x.r.name||"")+'</div><small>Всего: '+x.q+' · Смонтировано: '+x.done+' · Осталось: '+Math.max(0,x.q-x.done)+'</small></div>'});body+='</div>';h=body;}
 else if(active==="scheme")h=card("Монтажная схема",'<div class="empty">Статусы схемы появятся после загрузки ведомости и выполненных работ.</div>');
 else if(active==="dynamics")h=card("Динамика",'<div class="empty">Динамика появится после заполнения выполненных работ.</div>');
 else if(active==="photos")h=card("Фотоотчёт",'<div class="empty">Фотоотчёт будет восстановлен отдельным следующим шагом.</div>');
 $("#view").innerHTML=h;
 bind();
}
function bind(){
 document.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>{active=b.dataset.v;render()});
 document.querySelectorAll("[data-field]").forEach(e=>e.oninput=()=>{let p=e.dataset.field.split("."),o=d;for(let i=0;i<p.length-1;i++)o=o[p[i]];o[p.at(-1)]=e.value;save()});
 document.querySelectorAll("[data-item]").forEach(e=>e.oninput=()=>{let [n,i,k]=e.dataset.item.split(":");d[n][+i][k]=e.value;save()});
 document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{let n=b.dataset.add;d[n].unshift(makers[n]());save();render()});
 document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{let [n,i]=b.dataset.del.split(":");d[n].splice(+i,1);save();render()});
 document.querySelectorAll("[data-bom-filter]").forEach(b=>b.onclick=()=>{let f=b.dataset.bomFilter;document.querySelectorAll(".bomrow").forEach(r=>{r.style.display=f==="all"||r.dataset.state===f||(f==="left"&&r.dataset.state==="partial")?"":"none"})});
 document.querySelectorAll("[data-inv-add]").forEach(b=>b.onclick=()=>{let inv=d.invoices[+b.dataset.invAdd];inv.items=inv.items||[];inv.items.push({type:"",code:"",name:"",mark:"",qty:"",unit:"",per:""});save();render()});
 document.querySelectorAll("[data-inv-del]").forEach(b=>b.onclick=()=>{let [di,ii]=b.dataset.invDel.split(":");d.invoices[+di].items.splice(+ii,1);save();render()});
 document.querySelectorAll("[data-inv]").forEach(e=>e.onchange=()=>{let [di,ii,k]=e.dataset.inv.split(":"),x=d.invoices[+di].items[+ii];x[k]=e.value;if(k==="code"){let t=d.tasks.find(q=>q.code===e.value);if(t){x.type=t.type||x.type;x.unit=t.unit||x.unit}}save();render()});
  document.querySelectorAll("[data-work-add]").forEach(b=>b.onclick=()=>{let day=d.workDays[+b.dataset.workAdd];day.items=day.items||[];day.items.push({type:"",code:"",mark:"",name:"",axis:"",level:"",qty:"",unit:"",per:""});save();render()});
 document.querySelectorAll("[data-work-del]").forEach(b=>b.onclick=()=>{let [di,ii]=b.dataset.workDel.split(":");d.workDays[+di].items.splice(+ii,1);save();render()});
 document.querySelectorAll("[data-work]").forEach(e=>e.onchange=()=>{let [di,ii,k]=e.dataset.work.split(":"),x=d.workDays[+di].items[+ii];x[k]=e.value;if(k==="code"){let t=d.tasks.find(q=>q.code===e.value);if(t){x.type=t.type||x.type;x.unit=t.unit||x.unit}x.mark="";x.name="";x.per=""}if(k==="mark"){let t=d.tasks.find(q=>q.code===x.code&&(q.type===x.type||!x.type))||d.tasks.find(q=>q.code===x.code),r=(t?.bom||[]).find(q=>q.mark===e.value);if(r){x.name=r.name||"";x.unit=t.unit||"тн";x.per=x.unit==="тн"?(Number(r.weight1)||0)/1000:Number(r.weight1)||0}}save();render()});

 document.querySelectorAll("[data-bom-clear]").forEach(b=>b.onclick=()=>{let t=d.tasks[+b.dataset.bomClear];t.bom=[];t.bomName="";save();render()});
 document.querySelectorAll("[data-bom]").forEach(inp=>inp.onchange=async()=>{let f=inp.files&&inp.files[0];if(!f)return;let bom;if(/\\.xlsx$/i.test(f.name))bom=await parseXlsx(f);else{let text=await f.text(),lines=text.split(/\\r?\\n/).filter(x=>x.trim()),sep=(lines[0]||"").includes(";")?";":(lines[0]||"").includes("\\t")?"\\t":",";bom=rowsToBom(lines.map(x=>x.split(sep).map(v=>v.trim().replace(/^"|"$/g,""))))}let t=d.tasks[+inp.dataset.bom];t.bom=bom;t.bomName=f.name;save();render()});

}
function legacy(print){localStorage.setItem("atemir_v9",JSON.stringify(d));location.href="legacy-report.html?object="+encodeURIComponent(id)+(print?"&print=1":"")}
$("#htmlExport").onclick=()=>legacy(false);$("#pdfExport").onclick=()=>legacy(true);render();
})();