(()=>{"use strict";
const id=new URLSearchParams(location.search).get("object")||"default", objects=JSON.parse(localStorage.getItem("atemir-company-objects-v1")||"[]"), obj=objects.find(x=>String(x.id)===String(id))||{};
const KEY="atemir_v9__object_"+id, legacyKey="atemir_v9";
const blank=()=>({version:72,base:{objectName:obj.name||"",address:obj.address||"",client:obj.client||""},reportDate:"",weather:{location:"",temp:"",wind:"",precip:""},reportPhotos:[],actedDays:[],penalties:[],workTypes:[],tasks:[],deadlines:[],workDays:[],invoices:[],workers:[],responsibles:[{role:"",fio:"",collapsed:false}],equipment:[]});
let d;try{d=JSON.parse(localStorage.getItem(KEY)||"null")||blank()}catch(e){d=blank()}
["actedDays","penalties","workTypes","tasks","deadlines","workDays","invoices","workers","responsibles","equipment","reportPhotos"].forEach(k=>{if(!Array.isArray(d[k]))d[k]=blank()[k]});
const sections=[["home","Сводка"],["works","Выполненные работы"],["invoices","Поставки / накладные"],["tasks","Проект / объёмы"],["deadlines","Сроки"],["acted","Актированные дни"],["workers","Рабочие"],["responsibles","Ответственные"],["equipment","Техника"],["penalties","Штрафы"],["photos","Фотоотчёт"]];
let active="home", saveTimer;
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify({...d,reportPhotos:[]}));$("#saveState").textContent="Сохранено";clearTimeout(saveTimer)}
function dirty(){ $("#saveState").textContent="Сохраняем…";clearTimeout(saveTimer);saveTimer=setTimeout(save,250)}
function field(label,path,type="text"){let v=path.reduce((a,k)=>a?.[k],d)??"";return `<div><label>${label}</label><input data-path="${path.join(".")}" type="${type}" value="${esc(v)}"></div>`}
function card(title,body){return `<div class="card"><h2>${title}</h2>${body}</div>`}
function list(key,title,make,fields){let a=d[key];return `<div class="toolbar"><button class="primary" data-add="${key}">+ Добавить</button></div>${a.length?a.map((x,i)=>`<div class="card"><div class="rowhead"><b>${title} ${i+1}</b><button class="danger" data-del="${key}:${i}">Удалить</button></div><div class="grid">${fields.map(f=>`<div><label>${f[0]}</label><input data-item="${key}:${i}:${f[1]}" type="${f[2]||"text"}" value="${esc(x[f[1]]??"")}"></div>`).join("")}</div></div>`).join(""):`<div class="empty">Записей пока нет</div>`}
function render(){
 $("#objTitle").textContent=obj.name||d.base.objectName||"Объект";$("#pageTitle").textContent=sections.find(x=>x[0]===active)[1];$("#pageSub").textContent=obj.name||"";
 document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("on",b.dataset.v===active));
 let h="";
 if(active==="home"){let tw=d.workers.reduce((s,x)=>s+(parseInt(x.qty)||0),0),te=d.equipment.reduce((s,x)=>s+(parseInt(x.qty)||0),0),ps=d.penalties.reduce((s,x)=>s+(parseFloat(String(x.amount||0).replace(",","."))||0),0);h=card("Объект",`<div class="grid g3">${field("Наименование",["base","objectName"])}${field("Адрес",["base","address"])}${field("Заказчик",["base","client"])}${field("Дата отчёта",["reportDate"],"date")}${field("Температура, °C",["weather","temp"],"number")}${field("Ветер, м/с",["weather","wind"],"number")}</div>`)+card("Сводка",`<div class="stat"><div>Рабочих<b>${d.workers.length}</b></div><div>Техники<b>${d.equipment.length}</b></div><div>Дней работ<b>${d.workDays.length}</b></div><div>Штрафов<b>${d.penalties.length}</b></div></div>`);
 if(active==="works")h='<div class="toolbar"><button class="primary" data-add="workDays">+ Добавить день</button></div>'+(!d.workDays.length?'<div class="empty">Выполненных работ пока нет</div>':d.workDays.map((day,di)=>`<div class="card"><div class="rowhead"><b>Выполненные работы — ${day.date||"дата не указана"}</b><button class="danger" data-del="workDays:${di}">Удалить день</button></div><div class="grid"><div><label>Дата</label><input data-item="workDays:${di}:date" type="date" value="${esc(day.date||"")}"></div></div><div class="toolbar" style="margin-top:14px"><button class="small" data-addwork="${di}">+ Работа</button></div>${(day.items||[]).map((x,wi)=>`<div class="card" style="background:#f8fbfd"><div class="rowhead"><b>Работа ${wi+1}</b><button class="danger" data-delwork="${di}:${wi}">Удалить</button></div><div class="grid g3">${[["Вид работы","type"],["Шифр","code"],["Наименование","name"],["Марка","mark"],["Ось","axis"],["Отметка","level"],["Количество","qty","number"],["Ед.","unit"],["Кол-во в 1 шт.","per","number"]].map(f=>`<div><label>${f[0]}</label><input data-work="${di}:${wi}:${f[1]}" type="${f[2]||"text"}" value="${esc(x[f[1]]??"")}"></div>`).join("")}</div></div>`).join("")}</div>`).join(""));
 if(active==="invoices")h='<div class="toolbar"><button class="primary" data-add="invoices">+ Добавить накладную</button></div>'+(!d.invoices.length?'<div class="empty">Накладных пока нет</div>':d.invoices.map((inv,ii)=>`<div class="card"><div class="rowhead"><b>Накладная ${inv.number||ii+1}</b><button class="danger" data-del="invoices:${ii}">Удалить</button></div><div class="grid"><div><label>Дата</label><input data-item="invoices:${ii}:date" type="date" value="${esc(inv.date||"")}"></div><div><label>Номер</label><input data-item="invoices:${ii}:number" value="${esc(inv.number||"")}"></div></div><div class="toolbar" style="margin-top:14px"><button class="small" data-addinv="${ii}">+ Позиция</button></div>${(inv.items||[]).map((x,xi)=>`<div class="card" style="background:#f8fbfd"><div class="rowhead"><b>Позиция ${xi+1}</b><button class="danger" data-delinv="${ii}:${xi}">Удалить</button></div><div class="grid g3">${[["Вид работы","type"],["Шифр","code"],["Наименование","name"],["Марка","mark"],["Количество","qty","number"],["Ед.","unit"],["Кол-во в 1 шт.","per","number"]].map(f=>`<div><label>${f[0]}</label><input data-inv="${ii}:${xi}:${f[1]}" type="${f[2]||"text"}" value="${esc(x[f[1]]??"")}"></div>`).join("")}</div></div>`).join("")}</div>`).join(""));
 if(active==="tasks"){const n=v=>parseFloat(String(v??"").replace(",","."))||0,total=(q,p)=>n(q)*(n(p)||1),del=(t,c)=>d.invoices.flatMap(x=>x.items||[]).filter(x=>(x.code||"")===c&&(!(x.type||"")||(x.type||"")===t)).reduce((s,x)=>s+total(x.qty,x.per),0),done=(t,c)=>d.workDays.flatMap(x=>x.items||[]).filter(x=>x.type===t&&x.code===c).reduce((s,x)=>s+total(x.qty,x.per),0);let groups={};d.tasks.forEach(t=>{let k=(t.type||"")+"|||"+(t.code||"");if(!groups[k])groups[k]={type:t.type||"",code:t.code||"",volume:0,unit:t.unit||""};groups[k].volume+=n(t.volume)});h='<div class="toolbar"><button class="primary" data-add="tasks">+ Добавить проектный объём</button></div>'+list("tasks","Проектная позиция",()=>({type:"",code:"",volume:"",unit:"тн",collapsed:false}),[["Вид работы","type"],["Шифр","code"],["Проектный объём","volume","number"],["Ед.","unit"]]).replace(/^<div class="toolbar">[\\s\\S]*?<\\/div>/,"")+card("Проект → поставлено → выполнено → остаток",'<div class="tablewrap"><table><thead><tr><th>Вид работы</th><th>Шифр</th><th>Проект</th><th>Поставлено</th><th>Выполнено</th><th>Остаток</th><th>Ед.</th></tr></thead><tbody>'+Object.values(groups).map(t=>{let a=del(t.type,t.code),b=done(t.type,t.code);return `<tr><td>${esc(t.type||"—")}</td><td>${esc(t.code||"—")}</td><td>${t.volume}</td><td>${a||"—"}</td><td>${b||"—"}</td><td>${Math.max(0,t.volume-b)}</td><td>${esc(t.unit||"—")}</td></tr>`}).join("")+'</tbody></table></div>');}
 if(active==="deadlines"){const n=v=>parseFloat(String(v??"").replace(",","."))||0,total=(q,p)=>n(q)*(n(p)||1),done=(t,c)=>d.workDays.flatMap(x=>x.items||[]).filter(x=>x.type===t&&x.code===c).reduce((s,x)=>s+total(x.qty,x.per),0),today=new Date().toISOString().slice(0,10);let cards=d.deadlines.map(dl=>{let t=d.tasks.find(q=>q.code===dl.code&&(q.type===dl.type||!dl.type))||d.tasks.find(q=>q.code===dl.code),status="Нет проектного объёма",pct=0,cls="";if(t&&dl.start&&dl.date){let st=new Date(dl.start+"T12:00:00"),en=new Date(dl.date+"T12:00:00"),td=new Date(today+"T12:00:00"),days=Math.max(1,Math.floor((en-st)/86400000)+1),elapsed=td<st?0:(td>en?days:Math.floor((td-st)/86400000)+1),plan=Math.max(0,Math.min(100,elapsed/days*100)),vol=n(t.volume),fact=done(t.type,t.code);pct=vol?Math.max(0,Math.min(100,fact/vol*100)):0;let delta=fact-vol*plan/100;cls=Math.abs(delta)<.0001?"ontime":delta<0?"behind":"ahead";status=Math.abs(delta)<.0001?"По графику":delta<0?"Отставание "+Math.abs(delta).toFixed(2)+" "+(t.unit||""):"Опережение "+delta.toFixed(2)+" "+(t.unit||"")}return `<div class="schedule ${cls}"><div><b>${esc(dl.type||"Работа")}</b><small>${esc(dl.code||"")}</small></div><strong>${status}</strong><div class="bar"><i style="width:${pct}%"></i></div><small>${dl.start||"—"} → ${dl.date||"—"} · выполнено ${Math.round(pct)}%</small></div>`}).join("");h=list("deadlines","Срок",()=>({type:"",code:"",start:"",date:"",collapsed:false}),[["Вид работы","type"],["Шифр","code"],["Начало","start","date"],["Окончание","date","date"]])+card("График выполнения",cards||'<div class="empty">Добавьте сроки и проектные объёмы</div>');}
 if(active==="acted"){let work=new Set(d.workDays.filter(x=>x.date).map(x=>x.date)),act=new Set(d.actedDays.filter(x=>x.date).map(x=>x.date)),dates=[...work,...act].sort(),cal="";if(dates.length){let a=new Date(dates[0]+"T12:00:00"),z=new Date(dates[dates.length-1]+"T12:00:00"),cur=new Date(a.getFullYear(),a.getMonth(),1);while(cur<=z){let y=cur.getFullYear(),m=cur.getMonth(),days=new Date(y,m+1,0).getDate(),cells="";for(let i=1;i<=days;i++){let ds=y+"-"+String(m+1).padStart(2,"0")+"-"+String(i).padStart(2,"0"),cl=work.has(ds)&&act.has(ds)?"both":work.has(ds)?"work":act.has(ds)?"acted":"";cells+=`<span class="${cl}">${i}</span>`}cal+=`<div class="month"><b>${cur.toLocaleDateString("ru-RU",{month:"long",year:"numeric"})}</b><div class="days">${cells}</div></div>`;cur=new Date(y,m+1,1)}}h=list("actedDays","Актированный день",()=>({date:"",reason:"Ветер",value:"",from:"",to:"",collapsed:false}),[["Дата","date","date"],["Причина","reason"],["Значение","value"],["С","from","time"],["До","to","time"]])+card("Календарь работ",cal||'<div class="empty">Календарь появится после добавления дат</div>');}
 if(active==="workers"){let totalWorkers=d.workers.reduce((s,x)=>s+(parseInt(x.qty)||0),0);h=card("Рабочие на объекте",'<div class="stat"><div>Всего работников<b>'+totalWorkers+'</b></div></div>')+list("workers","Работники",()=>({name:"",qty:1}),[["Должность / профессия","name"],["Количество, чел.","qty","number"]]);}
 if(active==="responsibles")h=list("responsibles","Ответственное лицо",()=>({role:"",fio:"",collapsed:false}),[["Должность","role"],["ФИО","fio"]]);
 if(active==="equipment"){let totalEq=d.equipment.reduce((s,x)=>s+(parseInt(x.qty)||0),0);h=card("Машины и механизмы",'<div class="stat"><div>Всего единиц техники<b>'+totalEq+'</b></div></div>')+list("equipment","Техника",()=>({type:"Автокран 25 т",custom:"",qty:1}),[["Наименование","type"],["Свое наименование","custom"],["Количество","qty","number"]]);}
 if(active==="penalties"){let sum=d.penalties.reduce((s,x)=>s+(parseFloat(String(x.amount||0).replace(",","."))||0),0);h=card("Анализ штрафов за время выполнения",'<div class="stat"><div>Общая сумма<b>'+sum.toLocaleString("ru-RU")+' тг</b></div><div>Количество штрафов<b>'+d.penalties.length+'</b></div></div>')+list("penalties","Штраф",()=>({date:"",amount:"",responsible:"",reason:"",collapsed:false}),[["Дата","date","date"],["Сумма, тг","amount","number"],["Ответственный","responsible"],["За что штраф","reason"]]);}
 if(active==="photos")h=card("Фотоотчёт",'<div class="muted">Фото из существующего отчёта сохранены отдельно и не удаляются. Редактор фото будет перенесён следующим модулем без изменения формата.</div>');
 $("#view").innerHTML=h;
}
$("#nav").innerHTML=sections.map(x=>`<button data-v="${x[0]}">${x[1]}</button>`).join("");
$("#nav").onclick=e=>{let b=e.target.closest("[data-v]");if(b){active=b.dataset.v;render()}};
$("#view").addEventListener("input",e=>{let p=e.target.dataset.path;if(p){let ks=p.split("."),o=d;while(ks.length>1)o=o[ks.shift()];o[ks[0]]=e.target.value;dirty()}let q=e.target.dataset.item;if(q){let[k,i,f]=q.split(":");d[k][+i][f]=e.target.value;dirty()}let w=e.target.dataset.work;if(w){let[a,b,f]=w.split(":");d.workDays[+a].items[+b][f]=e.target.value;dirty()}let v=e.target.dataset.inv;if(v){let[a,b,f]=v.split(":");d.invoices[+a].items[+b][f]=e.target.value;dirty()}});
$("#view").addEventListener("click",e=>{let a=e.target.dataset.add;if(a){const makers={workDays:()=>({date:"",items:[],collapsed:false}),invoices:()=>({date:"",number:"",items:[],collapsed:false}),tasks:()=>({type:"",code:"",volume:"",unit:"тн",collapsed:false}),deadlines:()=>({type:"",code:"",start:"",date:"",collapsed:false}),actedDays:()=>({date:"",reason:"",value:"",from:"",to:"",collapsed:false}),workers:()=>({fio:"",role:"",qty:"",collapsed:false}),responsibles:()=>({role:"",fio:"",collapsed:false}),equipment:()=>({type:"",custom:"",qty:1,collapsed:false}),penalties:()=>({date:"",amount:"",responsible:"",reason:"",collapsed:false})};d[a].unshift(makers[a]());dirty();render()}let q=e.target.dataset.del;if(q){let[k,i]=q.split(":");d[k].splice(+i,1);dirty();render()}let aw=e.target.dataset.addwork;if(aw!==undefined){let day=d.workDays[+aw];day.items=day.items||[];day.items.push({type:"",code:"",name:"",mark:"",axis:"",level:"",qty:"",unit:"тн",per:"",photos:[]});dirty();render()}let dw=e.target.dataset.delwork;if(dw){let[a,b]=dw.split(":");d.workDays[+a].items.splice(+b,1);dirty();render()}let ai=e.target.dataset.addinv;if(ai!==undefined){let inv=d.invoices[+ai];inv.items=inv.items||[];inv.items.push({type:"",code:"",name:"",mark:"",qty:"",unit:"тн",per:""});dirty();render()}let di=e.target.dataset.delinv;if(di){let[a,b]=di.split(":");d.invoices[+a].items.splice(+b,1);dirty();render()}});
function openLegacy(print){save();localStorage.setItem(legacyKey,JSON.stringify(d));location.href="legacy-report.html?object="+encodeURIComponent(id)+(print?"&print=1":"")}
$("#htmlExport").onclick=()=>openLegacy(false);$("#pdfExport").onclick=()=>openLegacy(true);
addEventListener("beforeunload",save);render();
})();